### ISSUE TITLE
Traducir las operaciones a ARM

### ISSUE THREAD

**Issue by mredigonda** [mredigonda/Ita#3]
Tenemos todas las intrucciones posibles del lenguaje Pilot, lo que necesitamos, es, por cada instrucción de pilot, un conjunto de instrucciones en ARM que tenga el mismo efecto.
Por ejemplo, para la instrucción `E`, el equivalente sería `bx lr`. La operación de asignar una variable es parte de la tarea #2.

**Comment by gonzalogt** [comment]
v0 23           —--> STR #23 [ r0 ] //asignar el valor 23 en la dirección de r0
E                   —--> bx lr //retorno de la función
O                  —--> B  // salta a la etiqueta que recibe como argumento
L                    —--> // En ARM basta con escribir el nombre de la etiqueta
I < v1 v2 56 —--> CMP r0 r1
                                BLO 56

**Comment by nachocattoni** [comment]
Ay hola tengo cuenta

**Comment by mredigonda** [comment]
Excelente. Fijate el tema de cómo manejar los registros al llamar a printf/scanf, porque si la llamamos asi nomás, entonces vamos a perder el valor de los registros caller save (muy posiblemente perderíamos el valor de r0, que según tus implementaciones, se usa para la asignación de valores a variables).
Además, según cómo asignás valores a variables, sólo vas a poder tener una variable (porque se supone que no podés mover r0 desde Pilot, y por lo tanto siempre escribís el mismo valor), así que habría que mover el r0 o algo así para que quede completo eso.
Hola Nacho.

**Comment by gturconi** [comment]
Claro, printf puede llegar a modificar r0 pero para no perder el valor de r0 hay que almacenarlo previamente en el stack con: 

PUSH {R0}
BL printf     
POP {R0}
//PUSH y POP son sinónimos de STMDB y LDM

**Comment by mredigonda** [comment]
No te preocupes por el segundo párrafo, eso es parte de #2.
Está bien eso de pushear a la pila antes de llamar a printf, acordate que a printf también hay que pasarle parámetros que posiblemente vayan en r0, r1, r2 y r3, hay que averiguar cómo se maneja eso.
Creo que prácticamente estamos con esto, si tengo otra dificultad te la comento.
