### ISSUE TITLE
Agregar documentación

### ISSUE THREAD

**Issue by mredigonda** [mredigonda/Ita#5]
Hacer una investigación de distintas herramientas útiles para generar documentación desde el código fuente (escribirle comentarios a las funciones, tirar un comando, y que te genere una página linda con la descripción de las funciones dadas en los comentarios).

**Comment by gturconi** [comment]
Por lo que estuve leyendo, Doxygen funciona perfectamente para C y es el más popular, aunque también hay otras alternativas como:

DoxyS (gratuito) -->  hay que bajarlo de la página http://www.doxys.dk/, ejecutar el archivo "doxys", entrar al directorio doxys_docs y por último abrir el archivo index.html

Natural Docs (gratuito) ---> pero es una aplicación que solo se usa a través de la linea de comandos
